#!/bin/sh

echo Chain 2 from zipped binary link to referral
echo Args: "${@}"
# note that we just have a url (follow the ref), not a full link
echo 'ERROR: UPGRADE "chain3" NEEDED at height: 936: https://raw.githubusercontent.com/provenance-io/cosmovisor/main/testdata/repo/ref_zipped?checksum=sha256:3d370b9b483c779b6cbaa7dbd266da6cacf9eb8f29b0bfb66e16d4fa8ba02b3a module=main'
sleep 3
echo 'ERROR: CONSENSUS FAILURE!!! err="UPGRADE \"chain3\" NEEDED at height: 936: https://raw.githubusercontent.com/provenance-io/cosmovisor/main/testdata/repo/ref_zipped?checksum=sha256:3d370b9b483c779b6cbaa7dbd266da6cacf9eb8f29b0bfb66e16d4fa8ba02b3a" module=main'
sleep 4
echo 'Do not print'
