#!/bin/sh

echo "Running $0..."
echo Chain 2 from zipped binary link to referral
echo Args: "${@}"
# note that we just have a url (follow the ref), not a full link
echo 'ERROR: UPGRADE "chain3" NEEDED at height: 936: https://raw.githubusercontent.com/provenance-io/cosmovisor/mtps/dockerization/testdata/repo/ref_zipped?checksum=sha256:53a3d262c3994f24daff57538e8cdf769d8cf243b84cc2c983be56278f9f37f0 module=main'
sleep 3
echo 'ERROR: CONSENSUS FAILURE!!! err="UPGRADE \"chain3\" NEEDED at height: 936: https://raw.githubusercontent.com/provenance-io/cosmovisor/mtps/dockerization/testdata/repo/ref_zipped?checksum=sha256:53a3d262c3994f24daff57538e8cdf769d8cf243b84cc2c983be56278f9f37f0" module=main'
sleep 4
echo 'Do not print'
