#!/bin/sh

echo "Running $0..."
echo Chain 2 from zipped binary link to referral
echo Args: "${@}"
# note that we just have a url (follow the ref), not a full link
echo 'ERROR: UPGRADE "chain3" NEEDED at height: 936: https://github.com/provenance-io/cosmovisor/blob/d739b8f19955010ae23df3f26f0e5674d3910ed7/testdata/repo/ref_zipped?checksum=sha256:f9f7ceb22fe275b76d3bf95dd314df2e157f793561ea466da16e1fb42677be1e module=main'
sleep 3
echo 'panic: UPGRADE "chain3" NEEDED at height: 936: https://github.com/provenance-io/cosmovisor/blob/d739b8f19955010ae23df3f26f0e5674d3910ed7/testdata/repo/ref_zipped?checksum=sha256:f9f7ceb22fe275b76d3bf95dd314df2e157f793561ea466da16e1fb42677be1e module=main'
sleep 4
echo 'Do not print'
